global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'vehicle-price-prediction'
    static_configs:
      - targets: ['vehicle-price-prediction:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
